version: '3'
services:
  node:
    container_name: app
    restart: always
    build: .
    ports:
      - 80:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: